name: End-to-end tests
on: 
  # Runs on pushes targeting the default branch
  # push:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Karma and Cypress tests
      - run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
